Update contract CI to ensure docs & types are built (#163)
* feat: add CI & build script for clarigen

* fix: push generated types & docs

diff --git a/.github/workflows/contract-tests.yaml b/.github/workflows/contract-tests.yaml
--- a/.github/workflows/contract-tests.yaml
+++ b/.github/workflows/contract-tests.yaml
@@ -28,3 +28,15 @@ jobs:
       - name: Lint
         run: pnpm lint
         working-directory: ./contracts
+      - name: Generate contract docs and types
+        run: pnpm build
+        working-directory: ./contracts
+      - name: Ensure git is clean
+        id: gitStatus
+        run: git diff --no-ext-diff --exit-code
+        continue-on-error: true
+      - name: Error message if git is dirty
+        if: steps.gitStatus.outcome == 'failure'
+        run: |
+          echo "::error::Git is dirty. Make sure you ran \`make build\` before pushing."
+          exit 1
