ci updates

diff --git a/.github/workflows/rust-jobs.yaml b/.github/workflows/rust-jobs.yaml
--- a/.github/workflows/rust-jobs.yaml
+++ b/.github/workflows/rust-jobs.yaml
@@ -6,6 +6,10 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+env:
+  NODE_VERSION: 22.1.0
+  BUF_VERSION: 1.42.0
+
 jobs:
   lint:
     name: Lint
@@ -18,14 +22,14 @@ jobs:
       - uses: pnpm/action-setup@v4
       - uses: actions/setup-node@v3
         with:
-          node-version: 22.1.0
+          node-version: ${{ env.NODE_VERSION }}
           cache: "pnpm"
       - uses: arduino/setup-protoc@v3
         with:
           version: "25.3"
       - uses: bufbuild/buf-action@v1
         with:
-          version: 1.42.0
+          version: ${{ env.BUF_VERSION }}
           setup_only: true
       - uses: actions-rust-lang/setup-rust-toolchain@v1
         with:
@@ -37,11 +41,15 @@ jobs:
         run: cargo fmt --all -- --check
       - name: Lint (Clippy)
         run: cargo clippy -- -D warnings
+      - name: Lint (pnpm)
+        run: pnpm --recursive run lint
       - name: Lint (Protobuf)
         run: |
           cd protobufs
           buf format --diff --exit-code
           buf lint
+      - name: Typecheck (pnpm)
+        run: pnpm --recursive typecheck
 
   unit-tests:
     name: Run Unit Tests
@@ -57,7 +65,7 @@ jobs:
       - uses: pnpm/action-setup@v4
       - uses: actions/setup-node@v3
         with:
-          node-version: 22.1.0
+          node-version: ${{ env.NODE_VERSION }}
           cache: "pnpm"
       - uses: arduino/setup-protoc@v3
         with:
@@ -84,7 +92,7 @@ jobs:
       - uses: pnpm/action-setup@v4
       - uses: actions/setup-node@v3
         with:
-          node-version: 22.1.0
+          node-version: ${{ env.NODE_VERSION }}
           cache: "pnpm"
       - uses: arduino/setup-protoc@v3
         with:
@@ -99,4 +107,28 @@ jobs:
       - name: Run Integration Tests
         run: make integration-test
 
-    
+  contracts:
+    name: Run Contract Checks
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v4
+      - uses: pnpm/action-setup@v4
+      - uses: actions/setup-node@v3
+        with:
+          node-version: ${{ env.NODE_VERSION }}
+          cache: "pnpm"
+      - name: Install Package Dependencies
+        run: pnpm install
+        working-directory: ./contracts
+      - name: Generate Contract Docs and Types
+        run: pnpm build
+        working-directory: ./contracts
+      - name: Ensure Git is Clean
+        id: gitStatus
+        run: git diff --no-ext-diff --exit-code
+        continue-on-error: true
+      - name: Error Message if Git is Dirty
+        if: steps.gitStatus.outcome == 'failure'
+        run: |
+          echo "::error::Git is dirty. Make sure you ran \`make build\` before pushing."
+          exit 1
